_wandb:
    value:
        cli_version: 0.23.1
        e:
            hpucizr1dq0x2xqqex0btbumis1z3y43:
                apple:
                    ecpuCores: 4
                    gpuCores: 7
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "8589934592"
                codePath: playground.py
                codePathLocal: playground.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245075738624"
                        used: "136170889216"
                email: arjunprakash027@gmail.com
                executable: /Users/arjunprakashrao/Drive/projects/math_gpt/.venv/bin/python
                git:
                    commit: c7d0c445a1b300a88f7a49f9947b69d38a73663d
                    remote: https://github.com/hirthickraj2015/math_gpt.git
                host: MacBookAir
                memory:
                    total: "8589934592"
                os: macOS-26.3-arm64-arm-64bit
                program: /Users/arjunprakashrao/Drive/projects/math_gpt/playground.py
                python: CPython 3.12.11
                root: /Users/arjunprakashrao/Drive/projects/math_gpt
                startedAt: "2025-12-26T22:15:13.993667Z"
                writerId: hpucizr1dq0x2xqqex0btbumis1z3y43
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.12.11
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
architecture:
    value: GPT
batch_size:
    value: 64
block_size:
    value: 32
dropout:
    value: 0.1
eval_interval:
    value: 500
eval_iters:
    value: 200
learning_rate:
    value: 0.0005
max_iters:
    value: 20000
n_embd:
    value: 128
n_head:
    value: 4
n_layer:
    value: 4
task:
    value: arithmetic-solver
